{
  config,
  pkgs,
  lib,
  ...
}:

{
  home.packages = [
    pkgs.oh-my-zsh
    pkgs.zsh-autosuggestions
  ];


  programs.zsh = {
    enable = true;
    shellAliases = {
      ls = "lsd";
      l = "ls -l";
      la = "ls -a";
      lla = "ls -la";
      lt = "ls --tree";
      ll = "ls -l";
      cat = "bat -p";
      update = "sudo nixos-rebuild switch";
    };
    initContent = ''
        # This script was automatically generated by the broot program
        # More information can be found in https://github.com/Canop/broot
        # This function starts broot and executes the command
        # it produces, if any.
        # It's needed because some shell commands, like `cd`,
        # have no useful effect if executed in a subshell.
        function br {
            local cmd cmd_file code
            cmd_file=$(mktemp)
            if broot --outcmd "$cmd_file" "$@"; then
                cmd=$(<"$cmd_file")
                command rm -f "$cmd_file"
                eval "$cmd"
            else
                code=$?
                command rm -f "$cmd_file"
                return "$code"
            fi
        }

      function y() {
      	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
      	yazi "$@" --cwd-file="$tmp"
      	IFS= read -r -d "" cwd < "$tmp"
      	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
      	rm -f -- "$tmp"
      }

      alias f='eval $(_PR_LAST_COMMAND="$(fc -ln -1)" _PR_ALIAS="`alias`" _PR_SHELL="zsh" "pay-respects")'
command_not_found_handler() {
      eval $(_PR_LAST_COMMAND="$@" _PR_SHELL="zsh" _PR_ALIAS="`alias`" _PR_MODE="cnf" "pay-respects")
      }
      
      export LC_ALL=en_US.UTF-8
      export LANG=en_US.UTF-8
      export LANGUAGE=en_US.UTF-8


        source ~/.p10k.zsh
        POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
        export PATH=$PATH:~/.rd/bin
        #eval "$(zoxide init zsh)"
        export VOLTA_HOME=$HOME/.volta
        export VOLTA_FEATURE_PNPM=1
        export PATH=$VOLTA_HOME/bin:$PATH
        export KREW_ROOT=$HOME/.krew
        export PATH=$KREW_ROOT/bin:$PATH
        
        ##THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
        #export SDKMAN_DIR="$HOME/.sdkman"
        #[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
    '';
  };
  programs.zsh.oh-my-zsh = {
    enable = true;
    custom = "$HOME/.oh-my-zsh/custom/";
    plugins = [
      "git"
      "sudo"
      "dotenv"
      "gitignore"
      "kubectl"
      "zoxide"
    ];

#    theme = "robbyrussell";
    theme = "powerlevel10k/powerlevel10k";
  };

  home.shell.enableZshIntegration = true;

  # Set zsh as default shell on activation
  home.activation.make-zsh-default-shell = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    # if zsh is not the current shell
    PATH="/usr/bin:/bin:$PATH"
            ZSH_PATH="${config.home.homeDirectory}/.nix-profile/bin/zsh"
            if [[ $(getent passwd ${config.home.username}) != *"$ZSH_PATH" ]]; then
              echo "setting zsh as default shell (using chsh). password might be necessay."
              if grep -q $ZSH_PATH /etc/shells; then
                echo "adding zsh to /etc/shells"
                run echo "$ZSH_PATH" | sudo tee -a /etc/shells
              fi
              echo "running chsh to make zsh the default shell"
              run chsh -s $ZSH_PATH ${config.home.username}
              echo "zsh is now set as default shell !"
            fi
  '';

}
